name: clinica

volumes:
  clinica_volume:

services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 clinica.wsgi"

  db:
    image: mysql:latest
    env_file: .env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - clinica_volume:/var/lib/mysql